<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableComHosting>true</EnableComHosting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

</Project>
